[package]
name = "raptor_cdn"
version = "0.1.0"
authors = ["richk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raptorq = "1.6"
rand = "0.8"